name: Workflow for Codecov
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install project
        run: pip install .
      - name: Install pytest coverage
        run: pip install "pytest-cov==4.0.0"
      - name: Run tests and collect coverage
        run: pytest --cov abq_parser
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
